" Must be first
set nocompatible

" For Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" For color scheme and status bar
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" For project tree browser
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'

" For syntax checking
Plugin 'vim-syntastic/syntastic'

" For tags generation 
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'
Plugin 'majutsushi/tagbar'

" For fuzzy finding of files
Plugin 'ctrlpvim/ctrlp.vim'

" For working with git
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

" For inserting matching delimiters
Plugin 'Raimondi/delimitMate'

" For syntax highlighting
Plugin 'gabrielelana/vim-markdown'

" For taking down notes
Plugin 'vimwiki/vimwiki'

call vundle#end()
filetype plugin indent on

" ----- altercation/vim-colors-solarized settings -----
set background=dark
set t_Co=256
colorscheme molokai

" ----- bling/vim-airline settings -----
" Always show status bar
set laststatus=2
" Show PASTE if in paste mode
let g:airline_detect_paste=1
" Use patched font
let g:airline_powerline_fonts = 1
" Show airline for tabs too
let g:airline#extensions#tabline#enabled = 1
" Use the solarized theme for the Airline status bar
let g:airline_theme='molokai'

" ----- jistr/vim-nerdtree-tabs settings -----
" Open/close NERDTree Tabs with \t
nmap <silent> <leader>t :NERDTreeTabsToggle<CR>
" To have NERDTree always open on startup
let g:nerdtree_tabs_open_on_console_startup = 1

" Needed for plugins like Syntastic and vim-gitgutter 
" which put symbols in the sign column
hi clear SignColumn

" ----- scrooloose/syntastic settings -----
let g:syntastic_error_symbol = '✘'
let g:syntastic_warning_symbol = "▲"
augroup mySyntastic
  au!
  au FileType tex let b:syntastic_mode = "passive"
augroup END

" ----- xolox/vim-easytags settings -----
" Where to look for tags files
set tags=./tags;,~/.vimtags
" Sensible defaults
let g:easytags_events = ['BufReadPost', 'BufWritePost']
let g:easytags_async = 1
let g:easytags_dynamic_files = 2
let g:easytags_resolve_links = 1
let g:easytags_suppress_ctags_warning = 1

" ----- majutsushi/tagbar settings -----
" Open/close tagbar with \b
nmap <silent> <leader>b :TagbarToggle<CR>

" ----- airblade/vim-gitgutter settings -----
" In vim-airline, only display "hunks" if the diff is non-zero
let g:airline#extensions#hunks#non_zero_only = 1

" General Settings
set backspace=indent,eol,start
set ruler
set number
set showcmd
set incsearch
set hlsearch
set tabstop=4
set shiftwidth=4
set expandtab

" Turn on Syntax Highlighting
syntax on

" Enable Mouse Functionality
set mouse=a

" Display different types of white spaces.
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.,eol:¬

" Add a ruler at 80 and 120th column
set colorcolumn=80,120
highlight ColorColumn ctermbg=DarkGrey guibg=lightgrey

" WIP: Getting autocomplete functionality
set omnifunc=syntaxcomplete#Complete

" Highlight current cursor position
:hi CursorLine   cterm=NONE ctermbg=grey ctermfg=white guibg=grey guifg=white
:hi CursorColumn cterm=NONE ctermbg=grey ctermfg=white guibg=grey guifg=white
:nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
