#!/usr/bin/env bash

# TODO: Figure out a way to deal with the directory configuration --> a config file?
# TODO: Add instructions on how to set up everything --> provide a set-up script?
# TODO: Provide a bootstrap script that does the following:
#       - create the top-level script (together with short desc)
#       - create the script-specific folder
# TODO: Create a helper script that will chmod u+x all the newly-created scripts. Do so recursively?
# TODO: Document the file naming conventions and the separation of the various scripts into their directories
# TODO: Be able to disable certain scripts --> put this in the config file?

CRAQ_DIR="/Users/brianyen/Desktop/config/craq/top_level_scripts"

# Select a top-level script
SELECTED="$(find "$CRAQ_DIR" -maxdepth 1 -type f -exec basename {} \; `# find the top-level scripts (basename only)` \
    | sort \
    | grep '^_'                 `# select only files that start with _` \
    | sed 's@\.@ @g'            `# replace the . char with a space char` \
    | column -s ',' -t          `# separate by , char and display as columns` \
    |  fzf -i                   `# case insensitive` \
           --delimiter _ \
           --with-nth='2..'     `# together with --delimiter, removes the _ prefix for the top-level scripts` \
           --prompt="craq: " \
           --info=default \
           --layout=reverse \
           --tiebreak=index \
    | cut -d ' ' -f1)"

# Execute the selected top-level script
# Note: the `,*` is included because the top-level scripts
# have the `,short_desc.short_desc.short_desc...` suffix
eval "${CRAQ_DIR}/${SELECTED},*"
