# Change colours for ls command
export CLICOLOR=1

# For pyenv and pyenv virtualenv to work
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[36m\]\u\[\033[m\]: \[\e[34m\]\w\[\e[0m\] \[\e[33m\]\$(parse_git_branch)\[\e[0m\] >> "

# For convenience when copying to NUS Linux Computing Cluster
nusscplinux() {
  scp "$@" brianyen@xcnd10.comp.nus.edu.sg:/home/b/brianyen
}

nusscpsunfire() {
  scp "$@" brianyen@sunfire.comp.nus.edu.sg:/home/b/brianyen
}

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Fuzzy Finder (fzf) settings
alias fp="fzf --preview 'bat --color=always --style=numbers {}' --bind ctrl-u:preview-page-up,ctrl-d:preview-page-down"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# Fuzzy Git Diff (allows git diff to be displayed in fzf preview window with
# syntax highlighting
fgd() {
  git diff $@ --name-only | fzf -m --ansi --preview "git diff --cached $@ --color=always -- {-1}"
}

# Set Path for Go
export GOPATH=$HOME

# Set default editor to Vim
export EDITOR=vim
export VISUAL="$EDITOR"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Fix for MacOS Catalina (clang)
export CPLUS_INCLUDE_PATH=/usr/local/opt/llvm/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
export LIBRARY_PATH=$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib
