# Change colours for ls command
export CLICOLOR=1

# For pyenv and pyenv virtualenv to work
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[36m\]\u\[\033[m\]: \[\e[34m\]\w\[\e[0m\] \[\e[33m\]\$(parse_git_branch)\[\e[0m\] >> "
